health_care/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views
from . import views


urlpatterns = [

    path('',DashboardView.as_view(),name='dashboard'),
    path('user_register/',UseregisterView.as_view(),name='register'),
    path('user_login/',UserLoginview.as_view(),name='login'),
    path('user_logout/',UserLogoutview.as_view(),name='logout'),
    path('update_profile/',UpdateProfile.as_view(),name='update_profile'),
    path('update_hospital/',UpdateHospitalInfo.as_view(),name='hospital'),
    path('list_hospitals/',ListAllHospitals.as_view(),name="list_hopitals"),
    path('hospital_detail/<int:pk>/',HospitalDetail.as_view(),name='hospital_detail'),
    path('hospital_rating/<int:pk>/',HospitalStarRating.as_view(),name='hospital_rating'),
    path('timetable/',TimeTable.as_view(),name='timetable'),
    path('timetable_detail/<int:pk>/',TimeTableDetail.as_view(),name='timetable_detail'),
    path('delete_table/<int:pk>/',DeleteTimeTable.as_view(),name='delete_table'),
    path('archived_tables/',ListArchivedTimetables.as_view(),name='archived_tables'),
    path('expertise/',ExpertiseView.as_view(),name='expertise'),
    path('expertise_detail/<int:pk>/',ExpertiseDetailView.as_view(),name='expertise_detail'),
    path('delete_expertise/<int:pk>/',DeleteExpertise.as_view(),name='delete_expertise'),
    path('list_doctors/',ListAllDoctors.as_view(),name='list_doctors'),
    path('list_doctors_per_expertise/<int:pk>/',ListDoctorsAsExpertise.as_view(),name='list_doctors_per_expertise'),
    path('show_doctor_profile/<int:pk>/',ShowDoctorsProfile.as_view(),name='show_doctor_profile'),
    path('send_star_rating<int:pk>/',SendStarRating.as_view(),name='send_star_rating'),
    path('patient_profile/<int:pk>/',ShowPatientProfile.as_view(),name='patient_profile'),
    path('patient_information/<int:pk>/',PatientInformation.as_view(),name='patient_information'),
    path('list_patients/',ListPatients.as_view(),name='list_patients'),
    path('appointment/<int:pk>/',MakeAppointment.as_view(),name='appointment'),
    path('list_patient_appointment/',ListPatientAppointments.as_view(),name='list_patient_appointment'),
    path('list_patient_archived_appointment',ListPatientArchivedAppointments.as_view(),name='list_patient_archived_appointment'),
    path('cancel_appointment/<int:pk>/',CancelPatientAppointment.as_view(),name='cancel_appointment'),
    path('forbidden/',ForbiddenAccess.as_view(),name='forbidden'),
    path('search/',Search.as_view(),name='search'),
    path('send_message/<int:pk>/',SendMessage.as_view(),name='send_message'),
    path('reply_message/<int:pk>/',SendReplyMessage.as_view(),name='reply_message'),
    path('delete_message/<int:pk>/',DeleteMessage.as_view(),name='delete_message'),
    path('delete_reply/<int:pk>/',DeleteReply.as_view(),name='delete_reply'),
    path('modify_message/<int:pk>/',ModifyMessage.as_view(),name='modify_message'),
    path('modify_reply/<int:pk>/',ModifyReply.as_view(),name='modify_reply'),
    path('manage_user/<int:pk>/',ManageUser.as_view(),name='manage_user'),
    path('admin_profile/<int:pk>/',AdminDetail.as_view(),name="admin_profile"),
    path('manage_admin/',ManageAdmins.as_view(),name='manage_admin'),  
    path('read_notes/',ReadNotes.as_view(),name='read_notes'),
    path('set_notes_readed/',SetNotesToReaded.as_view(),name="set_notes_readed"),
    path('password_change/',ChangePasswordView.as_view(),name='change_password'),
    path('timetable_chart/',ActiveTimetable_Chart.as_view(),name="timetable_chart"),
    path('timetable_statistic/',TimeTableStatistic.as_view(),name="statistic_chart"),
    path('expertise_chart/',DoctorExpertiseChart.as_view(),name="expertise_chart"),
    path('appointment_chart/',DoctorAppointmentChart.as_view(),name='appointment_chart'),
    path('user_chart/',UserJoinedStatistic.as_view(),name='user_chart'),
    path('login_chart/',UserLoginStatistic.as_view(),name='login_chart'),
    path('password-reset/', ResetPasswordView.as_view(), name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='settings/password_reset_confirm.html'),name='password_reset_confirm'),
    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='settings/password_reset_complete.html'),name='password_reset_complete'),
    path('account_activation/<uidb64>/<token>', views.account_activation, name='account_activation'),
    path('twofactor_login/<uidb64>/',TwoFactorLogin.as_view(), name='twofactor_login'),
    path('calendar/',CalendarView.as_view(), name='calendar'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

from PIL import Image
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver
from django.contrib.auth.models import AbstractUser
from django.utils import timezone
from django.urls import reverse
from datetime import date
from random import randbytes
from django.contrib.auth.signals import user_logged_in
from django.db.models import F

from django.conf import settings
from tinymce.models import HTMLField
from colorfield.fields import ColorField
from django.db.models import Avg,Count

import datetime
from django.utils import timezone


class User(AbstractUser):


    email = models.EmailField(unique=True)

    USER_TYPE = (

        ('D', 'Doctor'),
        ('P', 'Patient'),
        ('A', 'Admin'),
    )
    type = models.CharField(max_length = 1, choices=USER_TYPE)

    def __str__(self):
        return self.username
    

@receiver(pre_save, sender=User)
def set_admin_pre_save(sender, instance, **kwargs):

    if instance.is_superuser:
        if not instance.type:
            instance.type = "A"


class TwoFactorAuth(models.Model):
    code = models.CharField(max_length=8)
    created_at = models.DateTimeField(auto_now_add=True)
    expiration = models.DateTimeField(null=True,blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.code}'


@receiver(post_save, sender=TwoFactorAuth)
def handler_function(sender, instance, created, **kwargs):
    if  created:
        instance.expiration = timezone.now() + timezone.timedelta(minutes=5)
        instance.save()



class LoginUpdate(models.Model):
    
    login_count = models.IntegerField(default=0)
    action_user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.action_user} login count: {self.login_count}'



@receiver(user_logged_in, sender=User)
def update_user_login(sender, **kwargs):
    user = kwargs.pop('user', None)
    user_login, created = LoginUpdate.objects.get_or_create(action_user=user)
    user_login.login_count = F('login_count') + 1
    user_login.save()
   

class Expertise(models.Model):

    name = models.CharField(max_length=250)
    description = HTMLField(blank=True,default="",max_length=3000)
    chart_color = models.CharField(max_length=7,blank=True,unique=True)

    def __str__(self):

        return self.name

# if admin not select any color get random one
@receiver(pre_save, sender=Expertise)
def expertise_pre_save(sender, instance, *args, **kwargs):
    color = f'#{randbytes(3).hex()}'
    if not instance.chart_color:
        instance.chart_color = color
    


class DoctorHospitalInfo(models.Model):


    name = models.CharField(max_length=200, unique=True)
    city = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    phone = models.CharField(max_length=20)
    image = models.ImageField(null=True,blank=True, upload_to='images/doctors/hospital')
    description = HTMLField(blank=True,default="",max_length=3000)

  

    def __str__(self):
        return self.name


    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        if self.image:
            img = Image.open(self.image.path)

            if img.height > 300 or img.width > 300:
                output_size = (300, 300)
                img.thumbnail(output_size)
                img.save(self.image.path)

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url
    

    @property
    def averagerate(self):
        review = HospitalRatio.objects.filter(hospital=self).aggregate(average=Avg('star_rating'))
        avg=0
        if review["average"] is not None:
            avg=float(review["average"])
        return avg
    
    @property
    def countrate(self):
        reviews = HospitalRatio.objects.filter(hospital=self).aggregate(count=Count('id'))
        cnt=0
        if reviews["count"] is not None:
            cnt = int(reviews["count"])
        return cnt



class DoctorProfile(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(null=True, blank=True, upload_to='images/doctors/avatar')
    bio = HTMLField(blank=True,default="",max_length=3000)
    phone = models.CharField(max_length=20)
    expertise = models.ManyToManyField(Expertise, blank=True)
    hospital = models.ForeignKey(DoctorHospitalInfo,on_delete=models.SET_NULL,blank=True,null=True)
    
    

    def __str__(self):

        return f'{self.user.first_name} {self.user.last_name}'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        if self.image:
            img = Image.open(self.image.path)

            if img.height > 300 or img.width > 300:
                output_size = (300, 300)
                img.thumbnail(output_size)
                img.save(self.image.path)


    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url
    

    @property
    def averagerate(self):
        review = DoctorsRatio.objects.filter(doctor=self).aggregate(average=Avg('star_rating'))
        avg=0
        if review["average"] is not None:
            avg=float(review["average"])
        return avg
    
    @property
    def countrate(self):
        reviews = DoctorsRatio.objects.filter(doctor=self).aggregate(count=Count('id'))
        cnt=0
        if reviews["count"] is not None:
            cnt = int(reviews["count"])
        return cnt

    
class DoctorTimeTable(models.Model):

    date = models.DateField(default=timezone.now)
    start_time = models.TimeField()
    end_time = models.TimeField()
    doctor = models.ForeignKey(DoctorProfile, on_delete=models.CASCADE)
    occupied = models.BooleanField(default=False)
    archived = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.doctor}-{self.date}-({self.start_time}-{self.end_time})'


    #to show patient appointment details in calendar
    @property
    def get_html_url(self):
        try:
            appointment = Appointment.objects.get(timetable=self.pk)
        except:
            appointment={}

        url = reverse('timetable_detail', args=(self.id,))
        if appointment:
            return f'<a href="/patient_profile/{appointment.patient.pk}/"><img data-toggle="tooltip" title="{appointment.patient.user.first_name} {appointment.patient.user.last_name}"  class="avatar avatar-lg ms-5 mt-2 border border-4 border-dark" src="{appointment.patient.imageURL}" /></a><a href="{url}">({self.start_time} - {self.end_time})</a>'
        else:
            return f'<a href="{url}">({self.start_time} - {self.end_time})</a>'


class PatientProfile(models.Model):

    
    GENDER = (
         
        ('M', 'Male'),
        ('F', 'Female'),
    )

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(null=True, blank=True, upload_to='images/patient/avatar')
    phone = models.CharField(max_length=20)
    city = models.CharField(max_length=250)
    address = models.CharField(max_length=250)
    age = models.PositiveIntegerField(null=True)
    gender = models.CharField(max_length=1,choices=GENDER,default="M")
   
    def __str__(self):

        return self.user.username

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        if self.image:
            img = Image.open(self.image.path)

            if img.height > 300 or img.width > 300:
                output_size = (300, 300)
                img.thumbnail(output_size)
                img.save(self.image.path)

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url
    


class TimetableLog(models.Model):

    date = models.DateTimeField(auto_now_add=True)
    entry = models.TextField(max_length=250)
    timetable = models.ForeignKey(DoctorTimeTable, on_delete=models.CASCADE)
    
    

    def __str__(self):
        return f'{self.date}-{self.entry}'
    

class PatientHealtInformation(models.Model):

    BLOOD = (
         
        ('A+', 'A+'),
        ('B+', 'B+'),
        ('AB+','AB+'),
        ('0+','0+'),
        ('A-', 'A-'),
        ('B-', 'B-'),
        ('AB-','AB-'),
        ('0-','0-'),
    )

    height = models.PositiveIntegerField(default="0")
    weight = models.PositiveIntegerField(default="0")
    blood_type = models.CharField(max_length=3,choices=BLOOD,default="0-")
    known_sickness = HTMLField(blank=True,default="",max_length=3000)
    medicines = HTMLField(blank=True,default="",max_length=3000)
    surgeries = HTMLField(blank=True,default="",max_length=3000)
    patient = models.OneToOneField(PatientProfile,on_delete=models.CASCADE,null=True)

 
class Appointment(models.Model):

    timetable = models.ForeignKey(DoctorTimeTable, on_delete=models.CASCADE)
    doctor = models.ForeignKey(DoctorProfile, on_delete=models.PROTECT)
    patient = models.ForeignKey(PatientProfile, on_delete=models.PROTECT)
    code = models.CharField(max_length=8, null=True)
    archived = models.BooleanField(default=False)

    def __str__(self):
        return  f'{self.doctor}-{self.patient}-{self.timetable}-{self.code}'
    

class Message(models.Model):

    sender = models.ForeignKey(User,related_name='sended',on_delete=models.CASCADE)
    receiver = models.ForeignKey(User,related_name='received',on_delete=models.CASCADE)
    body = HTMLField(blank=True,default="",max_length=3000)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.sender}-{self.receiver}'


@receiver(post_save, sender=Message)
def send_message_notification(sender, instance, created, **kwargs):

    url = settings.ABSOLUTE_URL_BASE

    if created:
        message = instance

main/templates/main/appointment.html
{% extends "main/base.html" %}

{% block content %}

<div id="layoutSidenav_content">
    <div class="container-fluid px-4 py-1">
    

    
    <h3 class="mt-4 py-5"><i class="fa-solid fa-handshake fa-lg"></i> Free appointment date ({{count}})</h3>
    
    <div class="row text-center">
        <a href=""><img  class="avatar avatar-xl ms-5 mt-2 border border-4 border-dark text-center" src="{{doctor.imageURL}}" /></a>
        <small class="ms-4">{{doctor.user.first_name}} {{doctor.user.last_name}}</small>
    </div>
    <table class="table border-2 border-primary">
  <thead>
    <tr>
      
      <th scope="col">Date</th>
      <th scope="col">Time</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  {% for table in  timetables%}
    <tr>
      
      <td>{{table.date}}</td>
      <td>{{table.start_time}} -- {{table.end_time}}</td>
      <td><button class="btn btn-warning btn-sm" data-bs-toggle="modal" data-bs-target="#bookModal-{{table.pk}}" >book</button></td>
    </tr>

            <!-- Modal -->
            <div class="modal fade" id="bookModal-{{table.pk}}" tabindex="-1" aria-labelledby="bookModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="bookModalLabel">Do you want to book this time slot</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    {{table.date}} {{table.start_time}} -- {{table.end_time}}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <form method="POST" action={% url 'appointment'  table.pk %}>
                    {% csrf_token %}
                    <button type="submit" class="btn btn-warning">Book</button>
                    </form>
                </div>
                </div>
            </div>
            </div>

    {% endfor %}
  </tbody>
</table>

                    {% if timetables.has_other_pages %}
                          <nav aria-label="Page navigation example">
                              <ul class="pagination pagination-sm mt-6 ms-8">
                                  {% if timetables.has_previous %}
                                  <li class="page-item"><a class="page-link text-white me-1 my-3" style="background-color:#4c1104;" href="?page={{timetables.previous_page_number}}">Previous</a></li>
                                  {% endif%}
                                  {% for page  in timetables.paginator.page_range %}
                                  <li class="page-item"><a class="page-link  text-white me-1 my-3" style="background-color:#4c1104;" href="?page={{page}}">{{page}}</a></li>
                                  {% endfor %}
                                  {% if timetables.has_next %}
                                  <li class="page-item"><a class="page-link  text-white me-1 my-3" style="background-color:#4c1104;" href="?page={{timetables.next_page_number}}">Next</a></li>
                                  {% endif %}
                              </ul>
                          </nav>
                      {% endif %}


    </div>
<div>




{% endblock content %}

main/templates/main/archived_timetables.html
{% extends "main/base.html" %}

{% block content %}

<div id="layoutSidenav_content">
<div class="container-fluid px-4 py-1">
<h3 class="mt-4 py-5"><i class="fa-regular fa-clock fa-lg"></i> Archived timeslots ({{count}})</h3>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Applicant</th>
      <th scope="col">Date</th>
      <th scope="col">hours</th>
      <th scope="col">settings</th>
      
    </tr>
  </thead>
  <tbody class="table-group-divider table-divider-color">
    {% for table in timetables%}
    <tr>
      <td>
      {% for applicant in table.appointment_set.all %}
      <a href="{% url 'patient_profile'  applicant.patient.pk %}">
      <img data-toggle="tooltip" title="{{applicant.patient.user.first_name}} {{applicant.patient.user.last_name}}"  class="avatar avatar-2lg ms-5 mt-2 border border-4 border-dark" src="{{applicant.patient.imageURL}}" />
      </a>
      {% endfor %}
      </td>
      <td>{{table.date}}</td>
      <td>{{table.start_time}}-{{table.end_time}}</td>
      <td>
      <button class="btn btn-outline-info btn-sm" 
      data-toggle="tooltip" data-bs-html="true" title="{% for info in table.timetablelog_set.all %}<p>{{info.entry}} ({{info.date}})</p> {% endfor %}" > 
      View log</button>
      </td>


    </tr>
    {% endfor %}
  </tbody>
</table>

                    {% if timetables.has_other_pages %}
                        <nav aria-label="Page navigation example">
                            <ul class="pagination pagination-sm mt-6 ms-8">
                                {% if timetables.has_previous %}
                                <li class="page-item"><a class="page-link text-white me-1 my-3" style="background-color:#4c1104;" href="?page={{timetables.previous_page_number}}">Previous</a></li>
                                {% endif%}
                                {% for page  in timetables.paginator.page_range %}
                                <li class="page-item"><a class="page-link  text-white me-1 my-3" style="background-color:#4c1104;" href="?page={{page}}">{{page}}</a></li>
                                {% endfor %}
                                {% if timetables.has_next %}
                                <li class="page-item"><a class="page-link  text-white me-1 my-3" style="background-color:#4c1104;" href="?page={{timetables.next_page_number}}">Next</a></li>
                                {% endif %}
                            </ul>
                        </nav>
                    {% endif %}

    <div class="control-group my-2 ms-1">
      <!-- Button -->
      <div class="controls">
        <a class="btn btn-outline-secondary btn-sm" href="{% url 'dashboard'%}">Go Back</a> 
      </div>
    </div>



</div>
</div>



{% endblock content %}

main/templates/main/expertise.html
{% extends "main/base.html" %}

{% block content %}

<div id="layoutSidenav_content">
<div class="container-fluid px-4 py-1">
<h3 class="mt-4 py-5">Current expertises </h3>
<table class="table">
  <thead>
    <tr>
      <th scope="col">name</th>
      <th scope="col">description</th>
      {% if request.user.is_staff %}<th scope="col">settings</th>{% endif%}
    </tr>
  </thead>
  <tbody class="table-group-divider table-divider-color">
    {% for expertise in expertises%}
    <tr>
 
      <td><a href="{% url 'list_doctors_per_expertise' expertise.pk %}"><small>{{expertise.name}} ({{expertise.doctorprofile_set.count}})</small></a></td>
      <td data-toggle="tooltip" data-bs-placement="bottom" data-bs-html="true"  title="{{expertise.description|safe}}">{{expertise.description|truncatechars:100|safe}}</td>
      {% if request.user.is_staff%}
      <td><a href="{% url 'expertise_detail' expertise.pk %}"  class="btn btn-outline-success btn-sm">Edit</a></td>
      <td>
      <button type="button" class="btn btn-danger btn-sm" data-bs-toggle="modal" data-bs-target="#deletemodal-{{expertise.pk}}">
      Delete
    </button>
      
      </td>
      {% endif %}
    </tr>

                <!-- Modal -->
                <div class="modal fade" id="deletemodal-{{expertise.pk}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                  <div class="modal-dialog">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h1 class="modal-title fs-5" id="deletemodal-{{expertise.pk}}">Do you want to delete this expertise?</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                      </div>
                      <div class="modal-body">
                        {{expertise}}
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-secondary btn-sm" data-bs-dismiss="modal">Back</button>
                        <form method="POST" action="{% url 'delete_expertise' expertise.pk  %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                        </form>
                      </div>
                    </div>
                  </div>
                </div>

    {% endfor %}
  </tbody>
</table>

                    {% if expertises.has_other_pages %}
                        <nav aria-label="Page navigation example">
                            <ul class="pagination pagination-sm mt-6 ms-8">
                                {% if expertises.has_previous %}
                                <li class="page-item"><a class="page-link text-white me-1 my-3" style="background-color:#4c1104;" href="?page={{expertises.previous_page_number}}">Previous</a></li>
                                {% endif%}
                                {% for page  in expertises.paginator.page_range %}
                                <li class="page-item"><a class="page-link  text-white me-1 my-3" style="background-color:#4c1104;" href="?page={{page}}">{{page}}</a></li>
                                {% endfor %}
                                {% if expertises.has_next %}
                                <li class="page-item"><a class="page-link  text-white me-1 my-3" style="background-color:#4c1104;" href="?page={{expertises.next_page_number}}">Next</a></li>
                                {% endif %}
                            </ul>
                        </nav>
                    {% endif %}

{% if request.user.is_staff%}
<form class="form-horizontal" enctype="multipart/form-data" method="POST">

{% csrf_token %}

<h3 class="mt-4 py-5">Add expertise</h3>

  <hr>
  {{form.as_table}}
  {{form.media}}
 
  <div class="control-group my-2">
      <!-- Button -->
      <div class="controls">
        <button class="btn btn-success btn-sm">update</button>
        <a class="btn btn-outline-secondary btn-sm" href="{% url 'dashboard'%}">Go Back</a>
        
      </div>
    </div>
</form>
{% endif %}

</div>
</div>






{% endblock content %}

main/templates/main/list_patient_appointment.html
{% extends "main/base.html" %}

{% block content %}

<div id="layoutSidenav_content">
    <div class="container-fluid px-4 py-1">

<h3 class="mt-4 py-5"><i class="fa-solid fa-handshake fa-lg"></i> Your {{title}} appointments ({{count}})</h3>
<table class="table shadow-custom">
  <thead>
    <tr>
      <th scope="col"></th> 
      <th scope="col">Doctor's name </th>
      <th scope="col">Date</th>
      <th scope="col">Time</th>
      <th scope="col">Location</th>
      <th scope="col"></th>
      <th scope="col">settings</th>
      
    </tr>
  </thead>
  <tbody>
  {% for appointment in appointments%}
    <tr>
      <td><a href="{% url 'show_doctor_profile' appointment.doctor.pk %}"><img  class="avatar avatar-2lg ms-5 mt-2 border border-4 border-dark" src="{{appointment.doctor.imageURL}}" /></a> </td>  
      <td>Dr. {{appointment.doctor.user.first_name}} {{appointment.doctor.user.last_name}}</td>
      <td>{{appointment.timetable.date}}</td>
      <td>{{appointment.timetable.start_time}} - {{appointment.timetable.end_time}}</td>    
      <td>{{appointment.doctor.hospital.city}} {{appointment.doctor.hospital.address}}</td>
      <td>
      <button class="btn btn-outline-info btn-sm" 
      data-toggle="tooltip" data-bs-html="true" title="{% for info in appointment.timetable.timetablelog_set.all %}<p>{{info.entry}} ({{info.date}})</p> {% endfor %}" > 
      View log</button>
       
      </td>
    {% if not appointment.archived %}  <td><button class="btn btn-danger btn-sm" data-bs-toggle="modal" data-bs-target="#cancelModal-{{appointment.pk}}" >Cancel</button></td>{% else %}<td></td> {% endif%}
    </tr>

        <!-- Modal -->
        <div class="modal fade" id="cancelModal-{{appointment.pk}}" tabindex="-1" aria-labelledby="cancelModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="cancelModalLabel">Do you want to cancel this appointment ?</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Dr. {{appointment.doctor.user.first_name}} {{appointment.doctor.user.last_name}} - {{appointment.timetable.date}} - {{appointment.timetable.start_time}} {{appointment.timetable.end_time}}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary btn-sm" data-bs-dismiss="modal">Close</button>
                <form method="POST" action="{% url 'cancel_appointment' appointment.pk   %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger btn-sm">Cancel appointment</button>
                </form>
            </div>
            </div>
        </div>
        </div>





  {% endfor %}
  </tbody>
</table>


                      {% if appointments.has_other_pages %}
                          <nav aria-label="Page navigation example">
                              <ul class="pagination pagination-sm mt-6 ms-8">
                                  {% if appointments.has_previous %}
                                  <li class="page-item"><a class="page-link text-white me-1 my-3" style="background-color:#4c1104;" href="?page={{appointments.previous_page_number}}">Previous</a></li>
                                  {% endif%}
                                  {% for page  in appointments.paginator.page_range %}
                                  <li class="page-item"><a class="page-link  text-white me-1 my-3" style="background-color:#4c1104;" href="?page={{page}}">{{page}}</a></li>
                                  {% endfor %}
                                  {% if appointments.has_next %}
                                  <li class="page-item"><a class="page-link  text-white me-1 my-3" style="background-color:#4c1104;" href="?page={{appointments.next_page_number}}">Next</a></li>
                                  {% endif %}
                              </ul>
                          </nav>
                      {% endif %}




</div>
</div>





{% endblock content %}